INSERT into USERS (USERNAME,PASSWORD,ENABLED) VALUES('user','$2a$10$wBlFuflxdDeM21apHDVm/uEVO88.XFj5QF0dAh5MaNiKSGdcE4wa6',1);

INSERT into ROLES (name) VALUES('USER');
INSERT into ROLES (name) VALUES('ADMIN');